# Generated by Django 5.1.1 on 2024-09-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_time', models.DateTimeField()),
                ('operation', models.CharField(max_length=10)),
                ('base_coin', models.CharField(max_length=10)),
                ('quote_coin', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
